// <auto-generated />
namespace Accentis.Database.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UPDATE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UPDATE));
        
        string IMigrationMetadata.Id
        {
            get { return "201808090840504_UPDATE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
